@id=c97a20fb-bdc5-4940-b0b5-815d09dcafa0
@token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYXJsb3N4bWVyY2EiLCJlbWFpbCI6ImNhcmxvc3htZXJjYSIsIm5iZiI6MTczMDM5NTkzMCwiZXhwIjoxNzMwMzk2NTMwLCJpYXQiOjE3MzAzOTU5MzAsImlzcyI6Iklzc3VlciIsImF1ZCI6IkF1ZGllbmNlIn0.aZeyHm2I4u1wWjgbHGJjMJNY3AOhZkDk56964Bce3y-5iVqE5zhqktosVo9EfghvhrS3gTW2JVOX8fOMsglx6w


GET http://localhost:5156/breakfasts/{{id}}
Authorization: Bearer {{token}}